sudo: required
language: python
python: '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl

install:
- pip install ansible==2.0.2.0
- pip install boto
- pip install --user awscli

script:
- openssl aes-256-cbc -K $encrypted_be9856372e02_key -iv $encrypted_be9856372e02_iv -in svaranasi-kp.enc -out svaranasi-kp -d
- chmod +x ec2.py ec2_pub.py
- chmod 400 svaranasi-kp
- export AWS_ACCESS_KEY_ID=$AK
- export AWS_SECRET_ACCESS_KEY=$SK
- export AWS_REGION="us-east-1"
- . ./deploy.sh

env:
  global:
  - AK=AKIAITJ3JO7IVNF4V3IA
  - secure: "oVAW4gZnS1SrjaGqocoXFSVNy5rSeQBowTuBOl5VCdnhN2P0AUhrK+GpfSYbAiPDuVt5eG/5QUcNHlgX0DIsCWjtJbglzuP4c6Fv7n6p71WluEy4x44UG/DP2MJQFudfBEpdt8EdAT20LPhp4g7viSATdUhXTun/8HjuVOq7xgfukewHluNL9yjz7+3ib+rWnDizZCWyF4SVqt6JTiKPhlZHRmG+6ysIng+gmlzQ91m4sxrJEwP1HEn+G7xGyPlsIvmTQbXnvzqX97XXK/aDIFxA563ugG4s0EZf3ZE7uHxnPEtvUYu00xdzh0FT69g2vKvOvbtBpLXshENGObzYhvs0q3R2dXjN3+CW4neMBcSF+2hMmxixSQr61UidBEEyOU4yyuO1YaST61b4ZXeIGpJ1cl9I2PRO9rWTXXWLChBti5qHyhT7sQYhfDulgd12t1jgk9joLfKNMTFfKNgmSheeENueqt8Pz4tY0WxIWR9ZfwBDV3yv+2C2hXhxtwktxGYiKDjXEWLa3t3Ea2xa/OKWakLi9etfqkNmAm5i+WMeOovpQxqhe2hy03r34uGRU66P+WL+73STTO07xDfbU50bho8ZZn79gMaT+fBoVL/nXLVfprTN5hfmveEt6J7EXDOtKou6Pt3Z1xbqb7KSlRvU32kURTrHS5eseQcP98s="
